insert into public.post_likes (likeid, postid, userid, liked_at)
values (default, 1, 1, default),
       (default, 2, 2, default),
       (default, 2, 3, default),
       (default, 1, 4, default),
       (default, 3, 5, default),
       (default, 3, 6, default),
       (default, 1, 7, default),
       (default, 4, 8, default),
       (default, 5, 9, default),
       (default, 6, 10, default),
       (default, 7, 1, default),
       (default, 7, 2, default),
       (default, 7, 3, default),
       (default, 7, 4, default),
       (default, 7, 5, default),
       (default, 4, 1, default),
       (default, 3, 3, default),
       (default, 5, 4, default);
